# Generated by Django 4.1.1 on 2022-09-05 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(validators=[django.core.validators.MinLengthValidator(5)])),
                ('email_id', models.EmailField(max_length=254)),
                ('company_code', models.CharField(max_length=5, unique=True)),
                ('strength', models.PositiveIntegerField(default=0)),
                ('website', models.URLField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
